"""Admin-only presentation for the in-process workflow analyzer.

This module supplies HTML only.  The caller is the main application handler;
there is no standalone server, API listener, or port configuration here.
"""
from __future__ import annotations


def page_html(api_path: str) -> str:
    """Return the compact analyzer page served by the main app."""
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Workflow Analyzer · Admin</title><style>
body{{margin:0;background:#0d141c;color:#edf4fa;font:15px system-ui}}.shell{{max-width:1180px;margin:auto;padding:28px 18px}}a{{color:#75d4ff}}h1{{margin:0 0 6px}}.note,.muted{{color:#9fb1c1}}.card{{background:#16212c;border:1px solid #314455;border-radius:12px;padding:18px;margin:18px 0}}.row{{display:grid;grid-template-columns:1fr 1fr 180px;gap:14px}}label{{display:grid;gap:6px;color:#c7d8e5;font-weight:650}}input,select{{padding:11px;border-radius:7px;border:1px solid #486078;background:#0d141c;color:white}}button{{margin-top:16px;padding:11px 16px;border:0;border-radius:7px;background:#37a7e7;color:#06131b;font-weight:800;cursor:pointer}}button:disabled{{opacity:.6;cursor:wait}}.step{{padding:12px;background:#101923;border-left:4px solid #55c4f5;border-radius:6px;overflow-wrap:anywhere;margin:8px 0}}.blocked{{border-left-color:#ff6060}}.arrow{{text-align:center;color:#67d7ff;font-size:20px}}.branch{{margin-left:18px;padding-left:14px;border-left:1px solid #486078}}.status-blocked{{color:#ff9b9b;font-weight:800}}.status-ok{{color:#80e7ad;font-weight:800}}table{{width:100%;border-collapse:collapse;font-size:13px}}th,td{{padding:9px;vertical-align:top;text-align:left;border-bottom:1px solid #314455;overflow-wrap:anywhere}}th{{color:#9fb1c1}}.table-wrap{{overflow:auto}}@media(max-width:760px){{.row{{grid-template-columns:1fr}}.table-wrap{{min-width:840px}}}}</style></head><body><main class="shell"><p><a href="/index/admin">← Admin dashboard</a></p><h1>Workflow Analyzer</h1><p class="note">Admin-only, read-only request inspection. Interactive verification is detected and never bypassed.</p><section class="card"><form id="analyzerForm"><div class="row"><label>Site URL<input name="siteUrl" type="url" required placeholder="https://example.com"></label><label>Movie page URL<input name="movieUrl" type="url" required placeholder="https://example.com/movie"></label><label>Quality<select name="quality"><option value="">All verified qualities</option><option value="480p">480p</option><option value="720p">720p</option><option value="1080p">1080p</option><option value="2160p">4K / 2160p</option></select></label></div><button id="analyzeButton">Analyze Workflow</button></form><p id="status" class="note"></p></section><section id="result" hidden><div class="card"><h2>Verified workflow</h2><p id="summary"></p><div id="flow"></div></div><div class="card"><h2>Execution log</h2><div class="table-wrap"><table><thead><tr><th>Request URL</th><th>Response</th><th>Redirect location</th><th>Link/button label</th><th>Source page</th><th>Reason followed</th><th>Extracted action</th><th>Next step</th></tr></thead><tbody id="log"></tbody></table></div></div></section></main><script>
const $=s=>document.querySelector(s),esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}}[c]));
function step(label,url,blocked=false){{return `<div class="step ${{blocked?'blocked':''}}"><b>${{esc(label)}}</b>${{url?`<div class="muted">${{esc(url)}}</div>`:''}}</div>`}}
$('#analyzerForm').onsubmit=async e=>{{e.preventDefault();const b=$('#analyzeButton'),status=$('#status');b.disabled=true;status.textContent='Executing bounded public HTTP requests…';$('#result').hidden=true;try{{const headers={{'content-type':'application/json'}},password=sessionStorage.getItem('adminPassword')||'';if(password)headers['x-admin-password']=password;const adminToken=new URLSearchParams(location.search).get('admin_token');if(adminToken)headers['x-admin-token']=adminToken;const response=await fetch('{api_path}',{{method:'POST',headers,body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}}),r=await response.json();if(!response.ok)throw Error(r.error||'Analyzer request failed');const blocked=r.status==='blocked';$('#summary').className=blocked?'status-blocked':r.status==='success'?'status-ok':'';$('#summary').textContent=`${{String(r.status||'partial').toUpperCase()}} — ${{r.message||''}}`;const results=r.results||[];$('#flow').innerHTML=step('Movie Page',r.movie_url)+results.map(x=>`<div class="arrow">↓</div>${{step(`${{x.quality||'Unknown'}} — ${{x.source||'Download branch'}}`,x.page_url,x.status==='blocked')}}<div class="branch"><div class="arrow">↓</div>${{step(x.status==='blocked'?(x.blocked_by==='cloudflare_turnstile'?'Cloudflare Turnstile':'Verification blocked'):x.is_final_file?'Final file URL reached':'Final file URL not reached',x.final_url||'',x.status==='blocked')}}</div>`).join('');$('#log').innerHTML=(r.execution_log||[]).map(x=>`<tr><td>${{esc(x.request_url)}}</td><td>${{esc(x.http_status)}}</td><td>${{esc(x.redirect_location||'None')}}</td><td>${{esc(x.link_button_label||'—')}}</td><td>${{esc(x.source_page||'—')}}</td><td>${{esc(x.reason_followed)}}</td><td>${{esc(x.extracted_action||'—')}}</td><td>${{esc(x.next_step)}}</td></tr>`).join('');$('#result').hidden=false;status.textContent='Analysis complete.'}}catch(error){{status.textContent='Error: '+error.message}}finally{{b.disabled=false}}}};
</script></body></html>'''
